# Generated by Django 3.1.2 on 2021-06-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willdo', '0002_auto_20201011_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='willdomodel',
            name='date',
        ),
    ]
