# Generated by Django 3.1.2 on 2021-06-22 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willdo', '0003_remove_willdomodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='willdomodel',
            name='day',
            field=models.DateField(default=datetime.date(2021, 6, 22)),
        ),
    ]
