# Generated by Django 3.1.2 on 2021-06-22 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willdo', '0004_willdomodel_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='willdomodel',
            name='day',
        ),
        migrations.AddField(
            model_name='willdomodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
