# Generated by Django 3.1.2 on 2021-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willdo', '0005_auto_20210622_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='willdomodel',
            name='create_user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
